language: node_js
node_js:
  - '13'
cache:
  directories:
    - node_modules
before_script:
  - npm install
  - npm install --prefix client
script:
  - npm run build
  - npm run test-client
deploy:
  provider: heroku
  app: cook-launch
  api_key:
    secure: ZVC2us5jhNQAca4/+L7HeKXJlF8yeafcIRUruaH0Ha2EGXi68Dln+W+2WbZBz3V1CDfknRRzpdECoDWe0G+dePrRnfQqTC/F2p9YNkyAfZVpXP4CnO7++InuGhVYbjQGEfeTW/VHVV0K5wuNZt1Qx8nLa5NsPpK5sKB9pyZ6xKVuSN76gjnC7qRZ3ugk+vM1aLv8zOnyLOt+mUtWkRjWktd7BgC6gHjfOup6XN+7qrKhvcAU+YPcZOIeaPC7cwByE2Zu1+tevA60182V8ceSlJBIvvALT5ZcteoBrrYQU3qMA7f5udOblmWUgsGnnMAJjxEk3nfdqpQD3tmD5wZWo0xBXjEpphj6D6RPXOPUE5FAsPpFWrL/NAkvmuTkRWTXgq1f+21i45hE3B6Os15R4DFwPgwbHztRvwGyucmQzgkGoE1y7YajWxtde/ojl0Jr+BmHDMbtIz2RyYE40njwx/V5WO1e28d6sIUSQXuItJgCeDcdgZzbc4tK41Xlh7JtraP/vFO7IPt94wgIoDVGFaPKJIEKXv2L44pEfAmvCYQC0G2t5MW0tE2piCeH2jiFk6A7gUPAuANIZebX/Ggf+cukj4sKkEjqCYOHvh+AJQA3WA8YD8ANoov7dmISUDw5CWVFmWfkUqCv4jMgiiBRwR4AmYjIx+g5aKp70oZTk2g=
